### ISSUE TITLE
OpenTelemetry Hooks

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/.github#16]
## Overview

The OpenTelemetry team has approved and merged feature flagging into the [semantic convention](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/feature-flags/). Since feature flags are dynamic and affect runtime behavior, it’s important to collect relevant feature flag telemetry signals. This can be used to determine the impact a feature has on a request, enabling enhanced observability use cases, such as A/B testing or progressive feature releases.

OpenFeature hooks should be created in each supported language.

## Requirements

Create an OTel hook for the following languages:

- [x] [OTel Hook for Node.JS](https://github.com/open-feature/js-sdk-contrib/pull/179)
- [x] [OTel Hook for Java](https://github.com/open-feature/java-sdk-contrib/issues/144)
- [x] [OTel Hook for .NET](https://github.com/open-feature/dotnet-sdk-contrib/issues/28)
- [x] [OTel Hook for Go](https://github.com/open-feature/go-sdk-contrib)
- [x] [OTel Hook for Python](https://github.com/open-feature/python-sdk-contrib/issues/7)
- [x] [OTel Hook for PHP](https://github.com/open-feature/php-sdk-contrib)
- [ ] [OTel Hook for Ruby](https://github.com/open-feature/ruby-sdk-contrib)

**Comment by tcarrio** [comment]
We can mark off the OTel hook for PHP now ✅
